### ISSUE TITLE
Inspect references and list properties instead of simply relying on toString()

### ISSUE THREAD

**Issue by 525c1e21-bd67-4735-ac99-b4b0e5262290** [alecperkins/coffeetable#15]
`window.location` (an instance of Location) simply results in `https://github.com/alecperkins/coffeetable/issues/new` whereas it should inspect the object and list its members.

**Comment by alecperkins** [comment]
If you 'finish' the object with a . then the auto-suggest will start inspecting it, eg `window.location.` will enumerate location in the auto-suggest. Actually being able to expand objects in the history that get returned as a result is already a todo with #4. I definitely agree it'll be helpful functionality. Until then, regular `console.log` and `console.dir` work, sending the output to the built-in console, and even have shortcuts in `log` and `dir`.
