### ISSUE TITLE
Expand objects when displayed in the history

### ISSUE THREAD

**Issue by alecperkins** [alecperkins/coffeetable#4]
Right now the objects are listed simply as [object Object], which is kind of useless. The user should be able to click on the object and have its properties enumerated.

See the Chrome console for an example.

**Comment by jussiry** [comment]
This indeed would be great. But until it gets implemented, would it be good to automatically log the results also to browsers console when the result is object? I know there are the 'log' and 'dir' shorthands, which are nice, but i think automatic logging could speed up the process a bit.

**Comment by alecperkins** [comment]
Good idea, and trivial to implement. But, I already have some prototype object expansion code about ready to go, so it's probably more worthwhile to just get that up and running. (Seeing that people are actually using this is pretty good motivation!) To make it available without having to wait for the other things marked for 0.3.0, I'll add it as a -dev version, available like the others. coffeetable-dev-min.js will always be the latest development code. I'll try to get this done tonight.

Sort of off-topic: It also is probably worth revisiting what's marked for versions, and split it up more perhaps.

**Comment by alecperkins** [comment]
I've added the object expansion, and it's available under http://code.alecperkins.net/coffeetable/coffeetable-dev.js (and will be part of 0.3.0). There's also a bookmarklet for that dev version on the docs page.

Please let me know if you run into any issues with it or would like it to behave differently.
